### ISSUE TITLE
[Bug]:  Issue with Package Names Containing "-"

### ISSUE THREAD

**Issue by daishuge** [Agora-X/Bing-Chat-API#2]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

could not import it because of it name

### Steps to reproduce the problem

> download it by pip
> try to import it

### What should have happened?

the name of the item may be **bing_chat* or another one with out * -*

### Version where the problem happens

Users will need to run this command to get the specific version they have installed

### What Python version are you running this with?

3.10

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
none
```

### Console logs

```Shell
nothing to say
```

### Additional information

In Python, a common convention is to use underscores (_) instead of hyphens (-) in package names to avoid such problems.

**Comment by EmersonJSC** [comment]
It appears that someone created a branch and fixed this issue that has been lingering without a resolution for quite some time.

**Comment by EmersonJSC** [comment]
Who created a branch and addressed this longstanding issue that has been unresolved for a while

**Comment by roberthobblebottom** [comment]
I also have the same error!  
  
I saw the latest commit and tried:  `pip3 install --upgrade bingchat` aka the latest name but I received this error:  
  
```
ERROR: Could not find a version that satisfies the requirement bingchat (from versions: none)
ERROR: No matching distribution found for bingchat
```

**Comment by daishuge** [comment]
> Who created a branch and addressed this longstanding issue that has been unresolved for a while

okay, thank you!
